/**
 * Stable machine-readable error codes for auth-layer failures.
 */
export const authErrorCodes = {
  OIDC_ACCESS_TOKEN_AUDIENCE_MISMATCH: "OIDC_ACCESS_TOKEN_AUDIENCE_MISMATCH",
  OIDC_ACCESS_TOKEN_CLAIMS_INVALID: "OIDC_ACCESS_TOKEN_CLAIMS_INVALID",
  OIDC_ACCESS_TOKEN_EXPIRED: "OIDC_ACCESS_TOKEN_EXPIRED",
  OIDC_ACCESS_TOKEN_INVALID: "OIDC_ACCESS_TOKEN_INVALID",
  OIDC_ACCESS_TOKEN_ISSUER_MISMATCH: "OIDC_ACCESS_TOKEN_ISSUER_MISMATCH",
  CLI_IDENTITY_SUB_MISMATCH: "CLI_IDENTITY_SUB_MISMATCH",
  CLI_USERINFO_FETCH_FAILED: "CLI_USERINFO_FETCH_FAILED",
  CLI_USERINFO_PARSE_FAILED: "CLI_USERINFO_PARSE_FAILED",
  CLI_USERINFO_SCHEMA_INVALID: "CLI_USERINFO_SCHEMA_INVALID",
  CLI_USERINFO_UNAUTHORIZED: "CLI_USERINFO_UNAUTHORIZED",
} as const;

/**
 * Union type for auth-layer error codes.
 */
export type AuthErrorCode = (typeof authErrorCodes)[keyof typeof authErrorCodes];
