/**
 * Stable machine-readable error codes for auth-layer failures.
 */
export const authErrorCodes = {
  ACCESS_SCOPE_FORBIDDEN: "ACCESS_SCOPE_FORBIDDEN",
  AUTHORIZATION_HEADER_MALFORMED: "AUTHORIZATION_HEADER_MALFORMED",
  AUTHORIZATION_HEADER_MISSING: "AUTHORIZATION_HEADER_MISSING",
  OIDC_ACCESS_TOKEN_AUDIENCE_MISMATCH: "OIDC_ACCESS_TOKEN_AUDIENCE_MISMATCH",
  OIDC_ACCESS_TOKEN_CLAIMS_INVALID: "OIDC_ACCESS_TOKEN_CLAIMS_INVALID",
  OIDC_ACCESS_TOKEN_EXPIRED: "OIDC_ACCESS_TOKEN_EXPIRED",
  OIDC_ACCESS_TOKEN_INVALID: "OIDC_ACCESS_TOKEN_INVALID",
  OIDC_ACCESS_TOKEN_ISSUER_MISMATCH: "OIDC_ACCESS_TOKEN_ISSUER_MISMATCH",
  OIDC_IDENTITY_SUB_MISMATCH: "OIDC_IDENTITY_SUB_MISMATCH",
  OIDC_USERINFO_FETCH_FAILED: "OIDC_USERINFO_FETCH_FAILED",
  OIDC_USERINFO_PARSE_FAILED: "OIDC_USERINFO_PARSE_FAILED",
  OIDC_USERINFO_SCHEMA_INVALID: "OIDC_USERINFO_SCHEMA_INVALID",
  OIDC_USERINFO_UNAUTHORIZED: "OIDC_USERINFO_UNAUTHORIZED",
} as const;

/**
 * Union type for auth-layer error codes.
 */
export type AuthErrorCode =
  (typeof authErrorCodes)[keyof typeof authErrorCodes];
