packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ^5.8.3
  tsup: ^8.4.0
  rimraf: ^6.0.1
  vitest: ^3.1.3

  zod: ^3.24.4
  neverthrow: ^8.2.0
  viem: ^2.29.4

  react: ^19.1.0
  react-dom: ^19.1.0
  next-themes: ^0.4.6
  lucide-react: ^0.507.0
  wagmi: 0.0.0-canary-20250516172625

  "@types/node": ^22.15.12
  "@types/react": ^19.1.3
  "@types/react-dom": ^19.1.3
