packages:
  - apps/*
  - packages/*

catalog:
  '@microsoft/api-extractor': ^7.55.1
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitest/browser': ^4.0.15
  '@vitest/browser-playwright': ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  dotenv-cli: ^11.0.0
  lucide-react: ^0.555.0
  neverthrow: ^8.2.0
  next-themes: ^0.4.6
  npm-run-all: ^4.1.5
  react: ^19.2.1
  react-dom: ^19.2.1
  rimraf: ^6.1.2
  tailwindcss: ^4.1.17
  tsup: ^8.5.1
  tsx: 4.21.0
  typescript: ^5.9.3
  viem: ^2.41.2
  vite: ^7.2.6
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.15
  wagmi: 3.1.0
  zod: ^4.1.13

onlyBuiltDependencies:
  - '@prisma/client'
  - esbuild
  - workerd
