packages:
  - apps/*
  - packages/*

catalog:
  '@microsoft/api-extractor': ^7.55.2
  '@prisma/adapter-pg': ^7.1.0
  '@prisma/client': ^7.1.0
  '@types/node': ^25.0.2
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitest/browser': ^4.0.15
  '@vitest/browser-playwright': ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  dotenv: ^17.2.3
  dotenv-cli: ^11.0.0
  inngest: ^3.48.1
  lucide-react: ^0.561.0
  neverthrow: ^8.2.0
  next-themes: ^0.4.6
  npm-run-all: ^4.1.5
  pg: ^8.16.3
  prisma: ^7.1.0
  react: ^19.2.3
  react-dom: ^19.2.3
  rimraf: ^6.1.2
  tailwindcss: ^4.1.18
  tsup: ^8.5.1
  tsx: 4.21.0
  typescript: ^5.9.3
  viem: ^2.42.1
  vite: ^7.3.0
  vite-tsconfig-paths: ^6.0.1
  vitest: ^4.0.15
  wagmi: 3.1.0
  zod: ^4.2.0

onlyBuiltDependencies:
  - '@prisma/client'
  - esbuild
  - workerd
