packages:
  - apps/*
  - packages/*

catalog:
  '@microsoft/api-extractor': ^7.52.13
  '@types/node': ^22.15.12
  '@types/react': ^19.1.3
  '@types/react-dom': ^19.1.3
  '@vitest/coverage-v8': ^3.2.4
  dotenv-cli: ^8.0.0
  lucide-react: ^0.507.0
  neverthrow: ^8.2.0
  next-themes: ^0.4.6
  npm-run-all: ^4.1.5
  react: ^19.1.0
  react-dom: ^19.1.0
  rimraf: ^6.0.1
  tailwindcss: ^4.1.5
  tsup: ^8.4.0
  tsx: 4.19.4
  typescript: ^5.8.3
  viem: ^2.29.4
  vitest: ^3.2.4
  wagmi: 0.0.0-canary-20250516172625
  zod: ^4.1.5
  vite-tsconfig-paths: ^5.1.4
