packages:
  - apps/*
  - packages/*

catalog:
  '@microsoft/api-extractor': ^7.56.0
  '@prisma/adapter-pg': ^7.3.0
  '@prisma/client': ^7.3.0
  '@types/node': ^25.2.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
  '@vitest/coverage-v8': ^4.0.18
  dotenv: ^17.2.3
  dotenv-cli: ^11.0.0
  inngest: ^3.50.0
  lucide-react: ^0.563.0
  neverthrow: ^8.2.0
  next-themes: ^0.4.6
  npm-run-all: ^4.1.5
  pg: ^8.18.0
  prisma: ^7.3.0
  react: ^19.2.4
  react-dom: ^19.2.4
  rimraf: ^6.1.2
  tailwindcss: ^4.1.18
  tsup: ^8.5.1
  tsx: 4.21.0
  typescript: ^5.9.3
  viem: ^2.45.1
  vite: ^7.3.1
  vite-tsconfig-paths: ^6.0.5
  vitest: ^4.0.18
  wagmi: 3.4.2
  zod: ^4.3.6

onlyBuiltDependencies:
  - '@prisma/client'
  - esbuild
  - workerd
