/**
 * Stable machine-oriented codes for domain-layer failures.
 */
export const domainErrorCodes = {
  AMOUNT_MUST_BE_POSITIVE: "DOM_AMOUNT_MUST_BE_POSITIVE",
  CURRENCY_CODE_FORMAT_INVALID: "DOM_CURRENCY_CODE_FORMAT_INVALID",
  CURRENCY_CODE_NOT_STRING: "DOM_CURRENCY_CODE_NOT_STRING",
  DATETIME_INVALID: "DOM_DATETIME_INVALID",
  DATETIME_NOT_DATE: "DOM_DATETIME_NOT_DATE",
  DECIMAL_INVALID_INPUT: "DOM_DECIMAL_INVALID_INPUT",
  DECIMAL_NOT_FINITE: "DOM_DECIMAL_NOT_FINITE",
  FEE_MUST_BE_NON_NEGATIVE: "DOM_FEE_MUST_BE_NON_NEGATIVE",
  FX_RATE_MUST_BE_POSITIVE: "DOM_FX_RATE_MUST_BE_POSITIVE",
  PRICE_MUST_BE_POSITIVE: "DOM_PRICE_MUST_BE_POSITIVE",
  TRANSACTION_ID_MISMATCH: "DOM_TRANSACTION_ID_MISMATCH",
  TRANSACTION_ID_NOT_EMPTY: "DOM_TRANSACTION_ID_NOT_EMPTY",
  TRANSACTION_TYPE_INVALID: "DOM_TRANSACTION_TYPE_INVALID",
  USER_ID_NOT_EMPTY: "DOM_USER_ID_NOT_EMPTY",
} as const;

/**
 * Machine code union used by domain-layer errors.
 */
export type DomainErrorCode =
  (typeof domainErrorCodes)[keyof typeof domainErrorCodes];
