export const cliErrorCodes = {
  CLI_API_REQUEST_FAILED: "CLI_API_REQUEST_FAILED",
  CLI_API_UNAUTHORIZED: "CLI_API_UNAUTHORIZED",
  CLI_AUTH_LOGIN_FAILED: "CLI_AUTH_LOGIN_FAILED",
  CLI_AUTH_REFRESH_FAILED: "CLI_AUTH_REFRESH_FAILED",
  CLI_AUTH_REVOKE_FAILED: "CLI_AUTH_REVOKE_FAILED",
  CLI_COMMAND_INVALID_ARGUMENT: "CLI_COMMAND_INVALID_ARGUMENT",
  CLI_CONFIG_INVALID: "CLI_CONFIG_INVALID",
  CLI_TOKEN_STORE_CLEAR_FAILED: "CLI_TOKEN_STORE_CLEAR_FAILED",
  CLI_TOKEN_STORE_READ_FAILED: "CLI_TOKEN_STORE_READ_FAILED",
  CLI_TOKEN_STORE_WRITE_FAILED: "CLI_TOKEN_STORE_WRITE_FAILED",
} as const;

export type CliErrorCode = (typeof cliErrorCodes)[keyof typeof cliErrorCodes];
